name: project
description: A new Flutter project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fl_chart: ^0.69.0

  flutter:
    sdk: flutter
  provider: ^6.1.2 # Cek versi terbaru di pub.dev
  sqflite: ^2.3.3 # Cek versi terbaru di pub.dev
  http: ^1.2.2



  # Package eksternal
  device_preview: ^1.1.0
  intl: any

  # Material Icons & Cupertino default
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
